services:
  #Responsável por enviar/distribuir/armazenar os nossos tópicos

  kafka:
    # Nome do container
    container_name: "kafka-notification-manager-service"
    # Imagem do Kafka
    image: confluentinc/cp-kafka:latest
    # Configuração de rede
    networks:
      - broker-kafka

    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Gerencia os brokers do Kafka - Gerencia os brokers
  zookeeper:
    container_name: "zookeeper-notification-manager-service"
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  #kafdrop é uma interface web para visualizar os tópicos do Kafka
  kafdrop:
    container_name: "kafdrop-notification-manager-service"
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  broker-kafka:
    driver: bridge